### ISSUE TITLE
Issue with Comments/Diff Color

### ISSUE THREAD

**Issue by AndrewDavis** [ferretwithaberet/lightless-theme#1]
Hi, Lightless Theme is my favorite VSCode theme that I've found so far. The only real problem I have with it is the color of the comments and/or diffs.

The comments, for one, are somewhat dark, a little *too* dark; it would be nice if they had more contrast. Also, and more importantly, they can be very difficult to see in a diff addition, due to having low contrast difference with that background color:

![image](https://user-images.githubusercontent.com/1561706/87041782-ba32e280-c1c0-11ea-8c7a-c356e0c9a195.png)

(The problem here is on the right side, not the left. ;)

**Comment by RadoiAndrei** [comment]
Hey, thank you for your feedback. At the moment the theme is just a combination of Deepdark by Nimbda and Material Theme by Mattia Astorino, in the future it might change a lot, as a temporary fix you could use [this](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) to customize the colors to your liking. But keep the feedback coming, we are more than happy to see people getting involved.

**Comment by AndrewDavis** [comment]
Thanks for getting back to me so quickly. Here's what I came up with:

```js
    "editor.tokenColorCustomizations": {
        "[Lightless Dark Theme]": {
            "comments": "#585858"
        }
    },
    "workbench.colorCustomizations": {
        "[Lightless Dark Theme]": {
            "diffEditor.insertedTextBackground": "#00a78a20",
            "diffEditor.removedTextBackground": "#a7008a20"
        }
    }
```

This makes the comments just light enough that you're encouraged to read them, but still keeps it in line with the dark theme I think.

It also changes the diff colors to look like this:
![image](https://user-images.githubusercontent.com/1561706/87045132-85755a00-c1c5-11ea-9817-5190b0df541c.png)
The transparencies on both colors were cut in half, that looks sooo much nicer. I also changed the red to purple (copying the green and just swapping the red + green channels); I personally like that better and think it fits Lightless Theme better but if not I'd go with `#a7001d20`, or something like that but maybe a different red.

**Comment by AndrewDavis** [comment]
While we're on this subject, I almost forgot that there was 1 other issue I had. I had code like this that looked kinda ugly, too much red:

![image](https://user-images.githubusercontent.com/1561706/87045784-47c50100-c1c6-11ea-8e57-a9ce5c0dc784.png)

Not quite sure what to do about that one, but yeah. Blegh.
